### ISSUE TITLE
29th October Youtube section

### ISSUE THREAD

**Issue by hristina-staykova** [uszilard/Team-Project-SAHK#18]
1. what will the user see before the search (initial content of the page)?
2. what will be shown after the search?
3. any issues?
4. extra info & ideas

**Comment by uszilard** [comment]
1. the user will get 4 random trending videos, on page load.
2. after search parameter is entered the user will see 4 videos in the context of what he is searching for
3. any specific issues - i will try to enable the option for full screen mode, now its only the small video working, and also in the trending section i would like to see music videos trending on page load.
4. will come back on this.

**Comment by hristina-staykova** [comment]
Making a new issue for 3. and closing this one as we are ok here
