### ISSUE TITLE
31st Oct #to get images from an api

### ISSUE THREAD

**Issue by karan96newbie** [uszilard/Team-Project-SAHK#26]
#to make ajax to get images

**Comment by hristina-staykova** [comment]
@karan96newbie which API are you using? 
1. what will the user see before the search (initial content of the page)?
2. what will be shown after the search?
3. any issues?
Please check this issue and leave your comment there - https://github.com/uszilard/Team-Project-SAHK/issues/5

**Comment by hristina-staykova** [comment]
we have it
