### ISSUE TITLE
29th October API basic calls - retrieving and displaying data

### ISSUE THREAD

**Issue by hristina-staykova** [uszilard/Team-Project-SAHK#5]
Let's try to make some API calls and get some data

**Comment by hristina-staykova** [comment]
@uszilard  @karan96newbie  Let us know when you made the calls and managed to retrieve data successfully.

**Comment by uszilard** [comment]
Managed to call data from YouTube API.

**Comment by hristina-staykova** [comment]
I got data from Napster for the news feed

**Comment by hristina-staykova** [comment]
Ana also has retrieved data successfully from Last.fm
@karan96newbie post your comment when you have a successful ajax call

**Comment by hristina-staykova** [comment]
We have pexels.com API from @karan96newbie, successful call & retrieving data, too. Closing this issue.
