### ISSUE TITLE
26th October Create basic JS file

### ISSUE THREAD

**Issue by hristina-staykova** [uszilard/Team-Project-SAHK#6]
To create the basics of our JS file/s - for API calls - let's start with three separate files that will deal with Youtube, Spotify, the Radio API
variables & functions, connect with the APIs, some basic thing that is working/connecting to the API

**Comment by uszilard** [comment]
Js file is in place, worked on it today, created the first AJAX for youtube.

**Comment by hristina-staykova** [comment]
We have now different files for the APIs, closing this issue.
